cameras:
    cv_8ed20433-57d5-4999-a6ab-0bea028b23a3:
        ffmpeg:
            inputs:
                - path: rtsp://127.0.0.1:8554/demo-74d51ead-aaea7c30
                  roles:
                    - detect
                    - record
        detect:
            enabled: true
            width: 1280
            height: 720
            fps: 10
        record:
            enabled: true
        snapshots:
            enabled: true
        lpr:
            enabled: true
        objects:
            track:
                - car
                - truck
                - motorcycle
                - bus
                - van
        live:
            streams:
                Live: cv_8ed20433-57d5-4999-a6ab-0bea028b23a3
        zones:
            cv_zone_0db48d65-49a4-4ae9-8a53-f438ece3edc7:
                coordinates: 0.6805,0.0791,0.6792,0.2101,0.9124,0.2791,0.9124,0.1053
            cv_zone_89e87a98-282e-46e8-ad1f-2ed0397a8f3d:
                coordinates: 0.0116,0.3357,0.9902,0.3643,0.9366,0.9833,0.0130,0.9833
    cv_9a3cd323-3820-46f0-aa5b-86c086a4a782:
        ffmpeg:
            inputs:
                - path: rtsp://127.0.0.1:8554/demo-74d51ead-1a7dd0c0
                  roles:
                    - detect
                    - record
        detect:
            enabled: true
            width: 1280
            height: 720
            fps: 10
        record:
            enabled: true
        snapshots:
            enabled: true
        lpr:
            enabled: false
        objects:
            track:
                - car
                - truck
                - motorcycle
                - bus
                - van
        live:
            streams:
                Live: cv_9a3cd323-3820-46f0-aa5b-86c086a4a782
    cv_55694d53-8f58-4981-91b2-7c6cd528a25d:
        ffmpeg:
            inputs:
                - path: rtsp://127.0.0.1:8554/demo-74d51ead-e774ae7a
                  roles:
                    - detect
                    - record
        detect:
            enabled: true
            width: 1280
            height: 720
            fps: 10
        record:
            enabled: true
        snapshots:
            enabled: true
        lpr:
            enabled: false
        objects:
            track:
                - car
                - truck
                - motorcycle
                - bus
                - van
        live:
            streams:
                Live: cv_55694d53-8f58-4981-91b2-7c6cd528a25d
        zones:
            cv_zone_9f60b7a1-7c66-4e88-a3a3-123bda12dcf2:
                coordinates: 0.0401,0.6306,0.3614,0.4551,0.8526,0.5351,0.4364,0.9862
                distances: 8.000,2.000,8.000,2.000
    cv_f691ef55-6791-495b-a35e-be215e7ac109:
        ffmpeg:
            inputs:
                - path: rtsp://127.0.0.1:8554/demo-74d51ead-f046692c
                  roles:
                    - detect
                    - record
        detect:
            enabled: true
            width: 1280
            height: 720
            fps: 10
        record:
            enabled: true
        snapshots:
            enabled: true
        lpr:
            enabled: false
        objects:
            track:
                - car
                - truck
                - motorcycle
                - bus
                - van
                - person
        live:
            streams:
                Live: cv_f691ef55-6791-495b-a35e-be215e7ac109
        zones:
            cv_zone_7c203f7c-be94-4756-95e1-97e46d939d12:
                coordinates: 0.0371,0.3286,0.5907,0.3286,0.6041,0.9786,0.0290,0.9762
            cv_zone_f28ed02d-5067-40c4-8883-be25e9a16530:
                coordinates: 0.0143,0.3071,0.6215,0.2952,0.6256,0.9857,0.0156,0.9786
database:
    path: /media/frigate/frigate.db
detect:
    enabled: true
    fps: 10
go2rtc:
    api:
        listen: :1985
    rtsp:
        listen: :8557
    streams:
        cv_8ed20433-57d5-4999-a6ab-0bea028b23a3:
            - rtsp://127.0.0.1:8554/demo-74d51ead-aaea7c30
            - ffmpeg:cv_8ed20433-57d5-4999-a6ab-0bea028b23a3#audio=opus
        cv_9a3cd323-3820-46f0-aa5b-86c086a4a782:
            - rtsp://127.0.0.1:8554/demo-74d51ead-1a7dd0c0
            - ffmpeg:cv_9a3cd323-3820-46f0-aa5b-86c086a4a782#audio=opus
        cv_55694d53-8f58-4981-91b2-7c6cd528a25d:
            - rtsp://127.0.0.1:8554/demo-74d51ead-e774ae7a
            - ffmpeg:cv_55694d53-8f58-4981-91b2-7c6cd528a25d#audio=opus
        cv_f691ef55-6791-495b-a35e-be215e7ac109:
            - rtsp://127.0.0.1:8554/demo-74d51ead-f046692c
            - ffmpeg:cv_f691ef55-6791-495b-a35e-be215e7ac109#audio=opus
lpr:
    enabled: true
mqtt:
    enabled: true
    host: 127.0.0.1
    port: 1884
objects:
    track:
        - car
        - truck
        - motorcycle
        - bus
        - van
record:
    enabled: false
    events:
        retain:
            default: 1
            mode: motion
    retain:
        days: 1
        mode: motion
snapshots:
    bounding_box: true
    enabled: true
    retain:
        default: 1
    timestamp: true
ui:
    unit_system: metric
